CREATE TABLE Properties (
    תמונה BLOB, 
    סדורי TEXT UNIQUE, 
    שם_secondary TEXT, 
    טלפון1 TEXT,
    נכס TEXT,
    חדר TEXT,
    מחיר TEXT,
    עיר TEXT,
    אז TEXT,
    רחוב TEXT,
    מס TEXT,
    קו TEXT,
    מע TEXT,
    עדכון TEXT,
    פתיחה TEXT,
    שכונה TEXT,
    סוכן TEXT,
    מ.שמש TEXT,
    בנוי TEXT,
    דרוג TEXT,
    טלפון2 TEXT,
    טלפון3 TEXT,
    רהוט TEXT, 
    חניה TEXT,
    סטטוס TEXT,
    פינוי TEXT,
    תקופה TEXT,
    חז_עו TEXT,
    שם_primary TEXT
);
